# Netlify configuration for ChefSpeak

[build]
  command = "npm run build"
  publish = "dist"

# SPA redirect rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(self), geolocation=()"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  autoLaunch = true
